version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - ./data/database.sqlite:/usr/src/autohome/data/database.sqlite
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
  queue:
    build:
      context: .
      dockerfile: ./docker/queue/Dockerfile
    volumes:
      - ./data/database.sqlite:/usr/src/autohome/data/database.sqlite
